apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.12.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: graphapp-api
  name: graphapp-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: graphapp-api
    spec:
      containers:
      - image: graphapp-api:latest
        name: graphapp-api
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
status: {}
