apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.12.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-express
  name: mongo-express
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongo-express
    spec:
      containers:
      - env:
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD_FILE
          value: /node_modules/mongo-express/secrets/mongopassword.txt
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME_FILE
          value: /node_modules/mongo-express/secrets/mongouser.txt
        image: mongo-express-img
        name: mongo-express
        ports:
        - containerPort: 8081
        resources: {}
        volumeMounts:
        - mountPath: /node_modules/mongo-express/secrets
          name: mongo-express-claim0
      restartPolicy: Always
      volumes:
      - name: mongo-express-claim0
        persistentVolumeClaim:
          claimName: mongo-express-claim0
status: {}
